name: Weather Notifier
on:
  schedule:
    - cron: '0 7 * * *'
  workflow_dispatch:

jobs:
  send_weather:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install dependencies
        run: pip install requests
      - name: Run notifier
        run: python weather_notifier.py
